### ISSUE TITLE
dont know if possible to add DoQ

### ISSUE THREAD

**Issue by hcarrega** [fyr77/dns-mobileconfig#13]
may you know better than me
thanks

**Comment by fyr77** [comment]
According to Apple documentation, DoQ is not yet supported: https://developer.apple.com/documentation/devicemanagement/dnssettings/dnssettings

`Possible values: HTTPS, TLS`

I will keep this issue open and will implement it as soon as DoQ is supported by Apple.

**Comment by hcarrega** [comment]
Hi again I think ios15 beta2 don't have quic on dnssettings

**Comment by fyr77** [comment]
It does not seem as if Apple will be implementing DoQ anytime soon. I am closing this issue for now and will reopen if necessary.

**Comment by hcarrega** [comment]
Im using quic via third party . AdGuard app ir surge5 
Thanks
