### ISSUE TITLE
Implement domain exclusions

### ISSUE THREAD

**Issue by fyr77** [fyr77/dns-mobileconfig#14]
I've tried implementing blacklists for domains, but failed to get it to work while testing.

In theory, [this](https://developer.apple.com/documentation/devicemanagement/dnssettings/ondemandruleselement/actionparameters) should disconnect from the ecnrypted DNS service when one of the domains is navigated to, but Safari and Firefox on iOS seem to completely ignore said list.

Testing was performed by creating a profile with an invalid DoT server name, which leads to no website loading. The excluded sites should then load fine, but they do not.
It could be possible that this feature is currently broken in iOS, but I am not sure.

**Comment by Gandulf78** [comment]
This one is working for my home made profile. It would be nice to have it implemented in your profile generator. 

 <key>OnDemandRules</key>
              <array>

                <dict>
                  <key>Action</key>
                    <string>Disconnect</string>
                  <key>SSIDMatch</key>
					<array>
						<string></string>
					</array>
                </dict>
                
				<dict>
					<key>Action</key>
					  <string>EvaluateConnection</string>
					<key>ActionParameters</key>
					<array>
						<dict>
							<key>DomainAction</key>
							<string>NeverConnect</string>
							<key>Domains</key>
							<array>
								<string>google.fr</string>
							</array>
						</dict>
					</array>
				</dict>                
                                
              </array>

**Comment by fyr77** [comment]
I am working on the implementation, but it will take a while longer because of university exams and deadlines. I expect to be able to properly work on it next month.

**Comment by fyr77** [comment]
Implemented in e0955b8f6ab339653e3137503da547a804fcf0c0, will be added in version 1.6 later today.

**Comment by fyr77** [comment]
New feature is now live. Closing this issue.
