### ISSUE TITLE
mobileconfig file downloads with .txt extension in some browsers

### ISSUE THREAD

**Issue by bnkas** [fyr77/dns-mobileconfig#16]
Hi there,

First, great work on this project.

I noticed that in some browsers, the mobileconfig file downloads with .txt extension. This appears to be caused by having `text/plain` mime type in your js files. 

To fix this, if possible, you can use `type: "application/octet-stream;charset=utf-8"` and the mobileconfig file appears to then download with the correct .mobileconfig in all browsers I tried. 

Thanks

**Comment by fyr77** [comment]
Hi! Thanks for the heads-up! 
I currently do not have much free time for working on my projects, but I will make this change as soon as I can.

**Comment by fyr77** [comment]
Wonderful, this fixes the problem with iOS 15! Implemented in f906f27a3b57fae3eef665d3527c9bf1748e8c48.
