### ISSUE TITLE
Profile signature

### ISSUE THREAD

**Issue by Gandulf78** [fyr77/dns-mobileconfig#20]
Thank you for this tool. 
It would be nice to generate signed profiles though. Or if not possible out of the box to provide guidelines to self-sign the profile. 
Is it something doable?
Thank you.

**Comment by fyr77** [comment]
I managed to get it working using a LetsEncrypt Certificate 🎉 
Implemented in 9309d95c0aa43bf263bf202e3cc01fa5562aa662 and will be pushed in the next version to the public website.
