### ISSUE TITLE
Adding "System wide" profile 

### ISSUE THREAD

**Issue by kansal15** [fyr77/dns-mobileconfig#24]
Hi,

Can we please add the "System wide" profile functionality in https://dns.notjakob.com/ as mentioned here - https://github.com/paulmillr/encrypted-dns/issues/22

**Comment by fyr77** [comment]
It seems this requires some more testing... I do not own a macOS device, so I cannot do so. One would need to install a regular certificate without the "system" scope, check network traffic, then install the same profile with "system" scope and check network traffic again.

I have created two files for 1.1.1.1 fulfilling these criteria (I think this usage is correct?) for testing: [1.1.1.1 test.zip](https://github.com/fyr77/dns-mobileconfig/files/11947987/1.1.1.1.test.zip)

**Comment by kansal15** [comment]
Mac with M1 chip are not using profiles, as mentioned here - https://github.com/paulmillr/encrypted-dns/issues/13

**Comment by kansal15** [comment]
> Mac with M1 chip are not using profiles, as mentioned here - [paulmillr/encrypted-dns#13](https://github.com/paulmillr/encrypted-dns/issues/13)
> 
> I can't check it by my own. I will try to check this from someone else machine.

Cisco Anyconnect agent was creating problem for mobileconfig. After uninstalling Anyconnect, mobile config starts working properly. 

Apps and terminal commands (like dig) are still using Do53. I will check your config file and will let you know.

**Comment by kansal15** [comment]
Not all apps are using DoT/DoH even with "System" config.

@fyr77 Agree with your views available here - https://github.com/paulmillr/encrypted-dns/issues/22#issuecomment-1620517284

**Comment by fyr77** [comment]
I added this feature to 1.7.0.
