### ISSUE TITLE
Dark Mode broken on Sign Profile

### ISSUE THREAD

**Issue by T0biii** [fyr77/dns-mobileconfig#25]
Dark Mode is broken if you click on the "?" on Sign Profile
![image](https://github.com/fyr77/dns-mobileconfig/assets/5702338/efde1a8a-0e16-4e67-8515-62255728e5be)

**Comment by fyr77** [comment]
Thank you for reporting this! 
Fixed in 1.6.3, which I will push in the next minutes to the webserver.
