### ISSUE TITLE
More pre-made DoH profiles

### ISSUE THREAD

**Issue by nitrohorse** [fyr77/dns-mobileconfig#3]
Hi, thanks for creating this. It’s really helpful! Please feel free to use any of the profiles I premade at https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs.

Cheers!

**Comment by fyr77** [comment]
Hi! Thanks for the link! I'll include it as soon as I have time.

**Comment by fyr77** [comment]
I have linked https://encrypted-dns.party/ in the menu bar, since adding all these profiles is rather time-consuming.

**Comment by fyr77** [comment]
Removed premades, implemented editing feature instead.
