### ISSUE TITLE
Additional options

### ISSUE THREAD

**Issue by fyr77** [fyr77/dns-mobileconfig#4]
NextDNS has some interesting options on their generator page. Might be worth looking into excluded Wifis and such.
https://apple.nextdns.io/

**Comment by vmstan** [comment]
I'd second this. I've manually copied some of the wifi exemptions out of a profile created off their page, to create my own custom profiles for Cloudflare, but having this in the tool would be really cool.

**Comment by fyr77** [comment]
It seems that the domain exclusion used by nextdns does not actually work. I couldn't get it to work even when using their domains. 

WiFi exclusion works perfectly fine, though.

**Comment by fyr77** [comment]
Someone named Renè contacted me on Telegram and sent me this article: https://nerd.one/vpn-on-demand-configuration-profiles-for-ios-and-macos-explained/

I will attempt to use the documentation provided there.

**Comment by vmstan** [comment]
Less code to manage then.

**Comment by fyr77** [comment]
added in 8c334e8fa604a0bc0963af46d991c9cd428d614c
