### ISSUE TITLE
ECDSA keys and certificates?

### ISSUE THREAD

**Issue by zero0ID** [fyr77/dns-mobileconfig#5]
Can the profile creator tool accommodate also ECDSA keys and certificates as described here:
https://blog.uncensoreddns.org/blog/33-hello-to-dns-over-https-and-ecdsa-keys/

**Comment by fyr77** [comment]
Currently not, but I will look into this in the next days.

**Comment by zero0ID** [comment]
Thank you!
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


4 Jan 2021, 10:38 by notifications@github.com:

**Comment by fyr77** [comment]
Alright, here's what I found from looking around a bit:

The configuration files themselves do not dictate what certificate to use. It seems that iOS will automatically select that, which means that if iOS supports ECDSA keys, all DNS configuration files generated with this tool will as well.
