### ISSUE TITLE
Unable to install DoT profile

### ISSUE THREAD

**Issue by zero0ID** [fyr77/dns-mobileconfig#6]
Created here (https://dns.notjakob.com/tool.html) a DoT profile but not possible to install it. (see att)
The downloaded DoH profiles from here (https://encrypted-dns.party/) were installed without any problem.

![0943488B-E523-4905-AB10-E75314F6FFFC](https://user-images.githubusercontent.com/76554148/103804609-b3433a80-5052-11eb-96cc-2d3e507c0e4c.jpeg)

**Comment by fyr77** [comment]
Thanks for the heads-up! This seems to be happening with DoT in general, perhaps Apple changed something about how it works in a recent update. I am looking into this.

**Comment by fyr77** [comment]
Alright, it seems to be a bug on my part, altough I am unsure how it came to be. The tool no longer imports DoT correctly. Working on a fix.

**Comment by fyr77** [comment]
Fixed in ebfa920a83f006f18db9252ca1279a3877c5e4f3

**Comment by fyr77** [comment]
Nevermind....

**Comment by fyr77** [comment]
Now it works. Apple seemingly changed ServerURL to ServerName when using DoT
