### ISSUE TITLE
Installation and connection issues

### ISSUE THREAD

**Issue by zero0ID** [fyr77/dns-mobileconfig#7]
Hello again

1)
Now it is possible to install the DoT profiles, but when installing a second one the previous disappears, i.e. 
installed successfully the Uncensored Unicast and then also successfully the Uncensored Anycast but the Unicast disappeared. The Uni and Any DoH profiles downloaded from Encrypted DNS Party installation is without problems.

2)
when checking the signing algorithms on https://rootcanary.org/test.html with the DoH profiles i get constantly only the GOST line and ECC GOST column unlocked. With the DoT looks weird, no idea if the check page is wrong or the DoT configuration. Do you have some address where to check the configuration please?

3)
Thank you!

![6A1A2FB8-28E6-44A9-83E5-7965CBAEFB98](https://user-images.githubusercontent.com/76554148/103878133-4cfffb80-50d6-11eb-9fde-3985a8423d12.jpeg)

**Comment by nitrohorse** [comment]
Regarding #1, I believe these fields need to be unique per profile, otherwise profiles would override one another.
- `PayloadIdentifier`
- `PayloadUUID`

Specifically I think the [`PayloadIdentifier`](https://github.com/fyr77/dns-mobileconfig/blob/main/js/tool.js#L124) needs to be unique the intention is for users to be able to generate and save multiple profiles. 🤔 

For #2, I'm not sure mobileconfig profiles make any difference here. They simply provide a way to securely connect to a DNS resolver. For questions related to https://rootcanary.org/test.html results I'd probably reach out to the DNS resolver maintainer directly.

**Comment by fyr77** [comment]
1. I can change the way profiles use identifiers, but why would you need multiple profiles installed at the same time? Wouldn't they override each other anyway?
2. The profiles created by this tool do not dictate any signing/algorithms, as @nitrohorse said. As far as I understand this, the results of the rootcanary test depends on the resolver. Also, I normally use https://1.1.1.1/help to check if the profiles work, as the AS Name will change even if not using Cloudflare's resolver.

But yeah, @nitrohorse pretty much said everything already.

**Comment by zero0ID** [comment]
1)
Seems that you misunderstand me. I want to install just 2 profiles, SecureDNS Unicast: DoT and DoH, not more. The problem is that when I install the second, DoH the previously installed DoT is deleted.
I will try to refresh the config page as @nitrohorse suggested.
2)
Roland v R... the admin of  https://rootcanary.org/ <https://rootcanary.org/test.html> said that based on random test results may be related to the fact that multiple DNS servers are involved. Maybe there is a misconfiguration on UncensoredDNS Unicast settings.

I will try also the newly released test version of DNSecure app by @kkk669 

-- 
Sent with Tutanota, the secure & ad-free mailbox: 
https://tutanota.com


8 Jan 2021, 12:30 by notifications@github.com:

**Comment by fyr77** [comment]
I see, I will update the website to allow you to install multiple profiles.

**Comment by fyr77** [comment]
Added functionality for multiple profiles in 03929e110abece2835b90258f666e664cedc1ec4

**Comment by fyr77** [comment]
Testing it on my iPad reveals that this might break it. Give me a few minutes.
