### ISSUE TITLE
Adding multiple DNS servers to one mobileconfig

### ISSUE THREAD

**Issue by PaulEwe** [fyr77/dns-mobileconfig#9]
Hello, I noticed it's possible to put more then one DNS Setting in a profile.
Just add `<dict><key>DNSSettings</key>
xx
</dict>` below the first setting inside the `<array>`.

Wouldn't it be smart then to add both DoT and DoH to one profile?

Thanks

**Comment by fyr77** [comment]
That seems possible, yes.
But why would you want to have both configured at once? It can only connect to DoH or DoT, or am I misunderstanding something? 
What is the use of having two configs active at the same time?

**Comment by PaulEwe** [comment]
Sorry for the late answer.
Also, maybe I should have specified myself a bit more.

Right now, to add multiple DNS servers to choose from on iOS (e.g. UncensoredDNS, Cloudflare malware & Adguard Adblock) you need to add another profile for every DNS server.

Having the option to add multiple DNS servers to one profile/mobileconfig would make it easier or respectively more efficient to manage every multiple DNS server.

After all, Apple did make `Settings -> General -> VPN & Network -> DNS` because they assumed folks have more then one DNS server configurated.

**Comment by fyr77** [comment]
I have implemented this functionality in 8157996, but it still needs polish and most importantly: it does not work on iOS at the moment.
For some reason cookies are not set - which are vital for this application.
I will work on this further of course.

**Comment by fyr77** [comment]
iOS not having a proper debugger makes this whole thing a lot harder than it has to be, but I'll find a way around.

**Comment by fyr77** [comment]
Alright, Chrome has the same behaviour on desktop, so I'll use that to debug.

**Comment by fyr77** [comment]
Issue seems to be fixed when deploying on a proper webserver. Deployed with Release 1.1
